version: '3'

services:
  db:
    image: "postgres:11"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /opt/hospitalite/hospitalite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/hospitalite
    ports:
      - 8000:8000
    depends_on:
      - db

  redis:
    image: "redis:5"
    ports:
      - 6379:6379

volumes:
  postgres_data: